export const axis = [
  {"id": 1, "name": "Vivienda", "description": "Creemos que la vivienda digna y asequible es un derecho humano y que elEstado tiene una responsabilidad de garantizar ese derecho."},
  {"id": 2, "name": "Salud Universal y cuidados", "description": "En Constituyentes creemos que el Estado debe garantizar el acceso a salud universal pública y gratuita para todas sus habitantes. También creemo que dos temas fundamentales para que exista tal universalización es el acceso a servicios públicos de salud mental y el acceso a servicios de salud en igualdad de condiciones para personas trans."},
  {"id": 3, "name": "Medio ambiente y movilidad", "description": "En Constituyentes creemos que la crisis climática, hídrica y de biodiversidad que enfrenta México es un tema prioritario. Proponemos concentrarnos como red en evitar el saqueo de agua por la industria. "},
  {"id": 4, "name": "Pueblos indígenas y afromexicanos", "description": "En Constituyentes creemos que es importante lograr mayor reconocimiento para las comunidades afromexicanas, así como contrarrestar la usurpación identitaria que sufren tanto las personas de pueblos indígenas como de comunidades afromexicanas para procurar el respeto de los derechos colectivos."},
  {"id": 5, "name": "Bienestar y programas sociales", "description": "En Constituyentes creemos que el Estado debe generar políticas públicas para elevar el bienestar de su población con énfasis en reducir desigualdades. Para impulsar este esfuerzo, desde la red queremos concentrarnos en lograr impulsar la participación de las personas beneficiarias en la planeación y evaluación de programas sociales y campañas de visibilización."},
  {"id": 6, "name": "Política laboral", "description": "En Constituyentes creemos que el Estado debe garantizar derechos laborales a personas en la formalidad y en la informalidad y ampliarlos progresivamente. A su vez, creemos que la democratización también debe llegar a los espacios de trabajo. Por ello buscaremos crear y ampliar espacios de defensa de derechos laborales, mejorar la cultura laboral y las prestaciones existentes."},
  {"id": 7, "name": "Política de drogas ", "description": "En Constituyentes hemos desarrollado una agenda en materia de política de drogas que busca transformar el enfoque punitivo y prohibicionista tradicional."},
  {"id": 8, "name": "Sistema de justicia", "description": "En Constituyentes creemos que es fundamental construir un mejor sistema de justicia donde todas las personas puedan acceder a su derecho a la justicia pronta y expedita. Por ellos buscaremos concentrarnos en aminorar algunos de los impactos nocivos de la reforma judicial y buscar incidir en el mejoramiento de las fiscalías."},
  {"id": 9, "name": "Sistema electoral y participación ciudadana ", "description": "Desde Constituyentes creemos que en una democracia más participativa, donde la ciudadanía pueda participar más allá de los partidos políticos. Por ello, nos concentraremos en impulsar un sistema electoral más abierto, y en fortalecer espacios de participación política no partidista."},
  {"id": 10, "name": "Seguridad ", "description": "Desde Constituyentes observamos con preocupación la grave crisis de seguridad en la que vive el país desde hace casi dos décadas. Desde donde nos toca como personas en organizaciones y colectivos de la sociedad civil o movimientos sociales, buscaremos concentrarnos en fortalecer los mecanismos de seguridad existentes"},
  {"id": 11, "name": "Migración ", "description": ""}
]

export const proposals = [
	{"axis": 1, "name": "Iniciar una base de datos pública y accesible de personas arrendatarias y arrendadoras para informar posibles Leyes de Renta y aumentos progresivos al predial. "},
	{"axis": 1, "name": "Monitorear la política pública de implementación de construcción de casas del INFONAVIT. "},
	{"axis": 1, "name": "Diseñar un programa de capacitación a servidores públicos municipales en temas de construcción con materiales sostenibles, accesibilidad para personas con discapacidad y desarrollo vertical. "},
	{"axis": 1, "name": "Impulsar acceso a nuevos materiales de construcción en reuniones con el INFONAVIT. "},
	{"axis": 1, "name": "Impulsar esfuerzos locales de cooperativas de vivienda "},
	{"axis": 1, "name": "Fortalecer esquemas de financiamiento comunitarios para liquidar créditos del INFONAVIT. "},
	{"axis": 1, "name": "Monitorear el nivel de accesibilidad de las viviendas construidas por INFONAVIT. "},
	{"axis": 1, "name": "Universalizar norma de construcción accesible. "},
	{"axis": 1, "name": "Generar acciones para presionar a que se fortalezca presupuestalmente CONAVI."},
	{"axis": 2, "name": "Hacer un diagnóstico y análisis profundo de las políticas públicas de salúd mental en el país y qué se puede mejorar. "},
	{"axis": 2, "name": "Incidir en que el sistema educativo existan las bases para la prevención, atención y socialización de la salud mental. "},
	{"axis": 2, "name": "Acompañar a organizaciones y activistas trans en un amparo colectivo para que puedan acceder a tratamientos hormonales a nivel estatal. "},
	{"axis": 2, "name": "Incidir en que exista el derecho a salud mental en la constitución. "},
	{"axis": 2, "name": "Incidir en la disminución de la pobreza menstrual. "},
	{"axis": 2, "name": "Incidir en el mejoramiento de la educación sexual "},
	{"axis": 2, "name": "Incidir en la implementación del Sistema Nacional de Cuidados. "},
	{"axis": 2, "name": "Mejorar las condiciones de las personas cuidadoras. "},
	{"axis": 2, "name": "Reconocer la interculturalidad en la salud"},
	{"axis": 2, "name": "Garantizar el derecho a un aborto libre y seguro. "},
	{"axis": 3, "name": "Fortalecer mecanismos de evaluación y vigilancia ciudadana en el tema de agua. "},
	{"axis": 3, "name": "Crear nuevos espacios de participación para democratizar decisiones en materia ambiental. "},
	{"axis": 3, "name": "Incidir en lograr la implementación de mecanismos de reparación del daño ambiental así como el cumplimiento de la regulación que protege a personas defensoras del territorio como el Acuerdo de Escazú."},
	{"axis": 3, "name": "Fortalecer esfuerzos ciudadanos de defensa de cuerpos de agua con una visión de cuenca. "},
	{"axis": 3, "name": "Promover sistemas de gestión integral de residuos con una perspectiva de reciclaje inclusivo. "},
	{"axis": 3, "name": "Impulsar la armonización de la Ley General de Movilidad y Seguridad Vial en los 32 estados."},
	{"axis": 4, "name": "Capacitar colectivos para la ejecución de campañas puerta a puerta con el objetivo de lograr un mayor reconocimiento en la intercensal de 2025."},
	{"axis": 4, "name": "Ofrecer capacitaciones en temas de cooperativismo para fortalecer la sostenibilidad de las comunidades. "},
	{"axis": 4, "name": "Acompañar el diseño de planes de desarrollo comunitario a nivel municipal. "},
	{"axis": 4, "name": "Desarrollar metodología para acompañar la planeación de desarrollo local en pueblos indígenas y afromexicanos."},
	{"axis": 5, "name": "Impulsar con personas legisladoras federales, estatales y gobiernos municipales que se abran espacios de participación de personas beneficiarias y colectivos de sociedad civil y movimientos sociales en el diseño y evaluación de programas sociales."},
	{"axis": 5, "name": "Generar una campaña de comunicación inclusiva, desde y para las personas con discapacidad. "},
	{"axis": 5, "name": "Diseñar una estrategia educativa de sensibilización sobre diversidad sexual de forma transversal. "},
	{"axis": 5, "name": "Incidir en la inclusión de personas mayores -vejez- más allá de los apoyos económicos, sino como sujetas de ideas, creatividad e ideas de política pública. "},
	{"axis": 5, "name": "Promocionar un modelo de crecimiento guiado por la economía social, y el crecimiento redistributivo. "},
	{"axis": 5, "name": "Impulsar una reforma fiscal progresista que permita ampliar programas sociales y gasto público en salud y cuidados."},
	{"axis": 6, "name": "Protección a gremios de comercio informal con un enfoque de Derechos Humanos para procurar a los y las trabajadoras que trabajan en la vía pública. "},
	{"axis": 6, "name": "Cuidar y difundir espacios de defensoría laboral mediante la elaboración de un catálogo público de mecanismos y una campaña para su difusión. "},
	{"axis": 6, "name": "Incidir en la reducción de la corrupción en los espacios que defienden derechos laborales. "},
	{"axis": 6, "name": "Impulsar iniciativas y acciones que reduzcan los horarios de trabajo (Bajar a 40 hrs a la semana), el reconocimiento y pago de las horas extras como parte de una sana cultura laboral. "},
	{"axis": 6, "name": "Incidir en la mejora de los ambientes laborales con las NOMS que existen. "},
	{"axis": 6, "name": "Mejorar protocolos o lineamientos para identificar la violencia laboral. "},
	{"axis": 6, "name": "Incidir en la mejora de prestaciones laborales. "},
	{"axis": 6, "name": "Incentivar a la iniciativa privada a contratar personas con discapacidad. "},
	{"axis": 6, "name": "Realizar campañas para que las personas con discapacidad puedan ocupar espacios de toma de decisión en materia laboral."},
	{"axis": 7, "name": "Modificar las políticas prohibicionistas, iniciando con la regulación del cannabis y estableciendo un marco legal que permita su producción, distribución y consumo de manera segura y controlada. Y que promueva un enfoque de justicia social."},
	{"axis": 7, "name": "Implementar políticas de reducción de riesgos y daños, enfocadas en minimizar las consecuencias negativas asociadas al consumo de sustancias. "},
	{"axis": 7, "name": "Priorizar la salud pública y los derechos humanos, promoviendo políticas de prioridad cero a nivel local para evitar la criminalización de las personas usuarias. "},
	{"axis": 7, "name": "Eliminar las barreras de acceso a servicios de salud y tratamiento para las personas que las utilizan. "},
	{"axis": 8, "name": "Incidir en la legislación secundaria de la reforma judicial para lograr que las elecciones sean más justas. "},
	{"axis": 8, "name": "Hacer diálogos nacionales para entender qué más falta en una reforma judicial integral incluyendo las fiscalías."},
	{"axis": 9, "name": "Incidir en el aumentó de acciones afirmativas en la próxima reforma electoral "},
	{"axis": 9, "name": "Fortalecer esfuerzos ciudadanos de participación política progresista. "},
	{"axis": 9, "name": "Fortalecer instrumentos estatales y municipales de participación ciudadana y democracia directa."},
	{"axis": 1, "name": "|Fortalecer mecanismos comunitarios de seguridad para personas activistas."},
	{"axis": 1, "name": "|Fortalecer el mecanismo de protección para personas defensoras de derechos humanos."},
	{"axis": 1, "name": "|Impulsar esfuerzos de construcción de paz. "},
	{"axis": 1, "name": "|Fortalecer esfuerzos de la sociedad civil para garantizar los derechos de las personas en movilidad y refugiadas. "}
]